services:
  postgres:
    image: postgres:18
    container_name: pgdatabase
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    volumes:
      - ny_taxi_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8085:80"
    depends_on:
      - postgres

  taxi_ingest:
    image: taxi_ingest:v001
    container_name: taxi_ingest_cont
    depends_on:
      - postgres
    command: 
      --pg-user=root
      --pg-pass=root
      --pg-host=postgres
      --pg-port=5432
      --pg-db=ny_taxi
      --year=2021
      --target-table=yellow_taxi_trips_2021__1

volumes:
  ny_taxi_postgres_data:
  pgadmin_data: